services:
  app:
    image: ghcr.io/cayanide/animerecommend:latest
    container_name: animerecommend_app
    ports:
      - "8000:8000"
    environment:
      - ANILIST_CLIENT_ID=${ANILIST_CLIENT_ID}
      - ANILIST_CLIENT_SECRET=${ANILIST_CLIENT_SECRET}
      - REDIRECT_URL=${REDIRECT_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  postgres:
    image: postgres:15
    container_name: animerecommend_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
